const workflow = [
  ["01", "Create an account", "Register once using your contact and home address details."],
  ["02", "Add your farm record", "Save your land location, crop, and farm information in one secure place."],
  ["03", "Submit and follow reports", "Send crop-damage concerns and receive MAO review updates."],
];

const services = [
  ["Farm profile", "Maintain land, crop, and farmer information that supports MAO services."],
  ["Damage report", "Send structured reports with clear photos, crop details, and incident location for MAO review."],
  ["Service updates", "View report status, MAO notices, and important farm-service reminders in one place."],
];

export function HomePage({ onNavigate }) {
  return <main className="min-h-screen bg-slate-50 text-slate-800">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-3"><button onClick={() => onNavigate("#home")} className="text-left leading-tight"><span className="block text-lg font-extrabold tracking-tight text-emerald-950">AgriSystem <span className="text-emerald-600">MAO</span></span><span className="mt-0.5 block text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Municipal Agriculture Office</span></button><nav className="flex items-center gap-2" aria-label="Public navigation"><button onClick={() => onNavigate("#login")} className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-100">Sign in</button><button onClick={() => onNavigate("#register")} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-emerald-800">Register</button></nav></div></header>
    <section className="relative isolate overflow-hidden border-b border-emerald-950 bg-gradient-to-br from-emerald-950 via-emerald-900 to-teal-800 px-5 py-12 text-white sm:py-16"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_84%_14%,rgba(190,242,100,.18),transparent_22rem),radial-gradient(circle_at_5%_92%,rgba(45,212,191,.16),transparent_28rem)]"/><div className="absolute -right-16 top-10 -z-10 h-64 w-64 rounded-full border border-lime-200/15"/><div className="absolute -right-5 top-20 -z-10 h-44 w-44 rounded-full border border-lime-200/10"/><div className="mx-auto grid max-w-7xl items-center gap-7 lg:grid-cols-[1.1fr_.9fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-emerald-200/25 bg-emerald-900/55 px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-lime-100"><span className="h-2 w-2 animate-pulse rounded-full bg-lime-300"/> Farmer services portal</p><h1 className="mt-5 max-w-3xl text-3xl font-extrabold leading-[1.12] tracking-tight sm:text-5xl">A clear path from farm concern to <span className="text-lime-300">MAO response.</span></h1><p className="mt-4 max-w-2xl leading-7 text-emerald-50/90">AgriSystem helps Bongabong farmers keep land records complete, document crop damage with clear evidence, and receive updates while MAO Staff review each concern.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => onNavigate("#register")} className="rounded-xl bg-lime-300 px-4 py-2.5 text-sm font-bold text-emerald-950 shadow-lg shadow-black/20 transition hover:-translate-y-0.5 hover:bg-lime-200">Create farmer account</button><button onClick={() => onNavigate("#login")} className="rounded-xl border border-white/25 bg-white/[.04] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-white/10">Sign in to portal</button></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-emerald-100"><span>✓ Land & crop records</span><span>✓ GPS-based reports</span><span>✓ MAO notifications</span></div></div><section className="rounded-2xl border border-white/15 bg-slate-950/20 p-5 shadow-2xl shadow-emerald-950/25 backdrop-blur-sm sm:p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-lime-200">Simple service flow</p><div className="mt-4 space-y-4">{workflow.map(([number, title, description]) => <article key={number} className="flex gap-4 rounded-xl border border-white/10 bg-white/[.04] p-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-lime-300 text-sm font-extrabold text-emerald-950">{number}</span><div><h2 className="font-bold text-white">{title}</h2><p className="mt-1 text-sm leading-6 text-emerald-50/80">{description}</p></div></article>)}</div></section></div></section>
    <section className="mx-auto max-w-7xl px-5 py-12 sm:py-16"><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Built for local farm support</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight text-slate-950 sm:text-3xl">Practical information, organized for every step.</h2></div><p className="max-w-2xl leading-7 text-slate-600">The portal keeps essential farm details and crop-damage reports together. Complete information, clear photos, and an accurate location help MAO Staff assess reports efficiently and give the farmer better guidance.</p></div><div className="mt-7 grid gap-4 md:grid-cols-3">{services.map(([title, description], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-emerald-200 hover:shadow-md"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-100 text-sm font-extrabold text-emerald-800">0{index + 1}</span><h3 className="mt-3 text-base font-bold text-slate-950">{title}</h3><p className="mt-1.5 text-sm leading-6 text-slate-600">{description}</p></article>)}</div><div className="mt-6 grid gap-3 rounded-2xl border border-emerald-100 bg-gradient-to-r from-emerald-50 to-lime-50 p-5 text-sm sm:grid-cols-3"><p><span className="font-bold text-emerald-800">For registration:</span> prepare your name, active contact number, email, address, profile photo, and land ownership proof.</p><p><span className="font-bold text-emerald-800">For farm records:</span> add land name, barangay, crop types, hectares, and correct map coordinates.</p><p><span className="font-bold text-emerald-800">For reports:</span> choose the affected land, describe the damage, add clear photos, and use your current GPS location.</p></div></section>
    <section className="border-y border-emerald-100 bg-emerald-50 px-5 py-10"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Farmer guide</p><h2 className="mt-2 text-2xl font-extrabold text-slate-950">What makes a useful crop-damage report?</h2><p className="mt-2 text-sm leading-6 text-slate-600">A complete report helps MAO Staff understand what happened and identify the information needed for proper validation.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-emerald-900">1. Before you report</p><p className="mt-2 text-sm leading-6 text-slate-600">Select the affected registered land. Prepare the crop name, visible damage, date it started, and the approximate affected area.</p></article><article className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-emerald-900">2. Take better evidence</p><p className="mt-2 text-sm leading-6 text-slate-600">Use daylight when possible. Include a wide photo of the field and close-ups of damaged leaves, stems, fruit, pests, or standing water.</p></article><article className="rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-emerald-900">3. Follow the review</p><p className="mt-2 text-sm leading-6 text-slate-600">Check My Reports and Notifications for MAO updates. Keep your contact number and email current so you do not miss guidance.</p></article></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><b>Important:</b> Camera suggestions help organize your report, but MAO Staff verify the final crop and damage assessment. Submit only accurate information and clear, recent farm photos.</div></div></section>
    <section className="px-5 py-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 rounded-2xl bg-slate-950 p-6 text-white md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-lime-300">Get started</p><h2 className="mt-2 text-xl font-extrabold">Ready to keep your farm record organized?</h2><p className="mt-1 max-w-xl text-sm text-slate-300">Register first, then add your land details before you submit a crop-damage report.</p></div><button onClick={() => onNavigate("#register")} className="shrink-0 rounded-xl bg-lime-300 px-4 py-2.5 text-sm font-bold text-emerald-950 transition hover:bg-lime-200">Register now</button></div></section>
    <footer className="border-t border-slate-200 bg-white px-5 py-5 text-center text-xs text-slate-500">Copyright 2026 AgriSystem - Municipal Agriculture Office</footer>
  </main>;
}
