import { useCallback, useEffect, useState } from "react";
import { api } from "../services/api.js";

const labels = { 0: "Clear", 1: "Mostly clear", 2: "Partly cloudy", 3: "Overcast", 45: "Foggy", 48: "Foggy", 51: "Light drizzle", 53: "Drizzle", 55: "Heavy drizzle", 61: "Light rain", 63: "Rain", 65: "Heavy rain", 80: "Rain showers", 81: "Rain showers", 82: "Heavy showers", 95: "Thunderstorm", 96: "Thunderstorm with hail", 99: "Thunderstorm with hail" };
const condition = code => labels[code] || "Current conditions";
const Metric = ({ label, value }) => <div className="rounded-xl border border-slate-100 bg-white p-3 shadow-sm"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div>;

export default function BongabongWeather({ token }) {
  const [data, setData] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const refresh = useCallback(async (background = false) => { if (!background) setLoading(true); setError(""); try { setData(await api("/weather/my-location", { token })); } catch (err) { setError(err.message || "Live weather is temporarily unavailable."); } finally { if (!background) setLoading(false); } }, [token]);
  useEffect(() => { refresh(); const timer = window.setInterval(() => refresh(true), 10 * 60 * 1000); return () => window.clearInterval(timer); }, [refresh]);
  const weather = data?.weather, today = data?.today;
  const conditionTime = data?.observedAt ? new Date(`${data.observedAt}+08:00`) : null;
  return <section className="mt-5 rounded-2xl border border-sky-100 bg-gradient-to-br from-sky-50 to-cyan-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-sky-700">Live weather today</p><h3 className="mt-1 font-extrabold text-slate-900">{data?.location || "Your registered farm"}</h3><p className="mt-1 text-xs text-slate-500">Based on the latitude and longitude saved for your farm land.</p></div><button type="button" onClick={() => refresh()} disabled={loading} className="rounded-lg border border-sky-200 bg-white px-3 py-2 text-xs font-bold text-sky-800 shadow-sm disabled:opacity-60">{loading ? "Updating..." : "Refresh now"}</button></div>{error ? <div className="mt-4 rounded-lg border border-red-100 bg-red-50 p-3 text-xs leading-5 text-red-700"><p>{error}</p><button type="button" onClick={() => refresh()} className="mt-2 font-bold underline">Try weather refresh again</button></div> : !weather ? <p className="mt-4 text-sm text-slate-500">Loading current conditions...</p> : <>{data?.notice && <p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-2 text-xs leading-5 text-amber-800">{data.notice}</p>}<div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Condition now" value={condition(weather.weather_code)}/><Metric label="Temperature" value={`${Math.round(weather.temperature_2m)}°C`}/><Metric label="Feels like" value={`${Math.round(weather.apparent_temperature)}°C`}/><Metric label="Humidity" value={`${weather.relative_humidity_2m}%`}/><Metric label="Wind now" value={`${Math.round(weather.wind_speed_10m)} km/h`}/><Metric label="Rain now" value={`${weather.rain || 0} mm`}/></div>{today && <div className="mt-4 rounded-xl border border-sky-100 bg-white/80 p-3"><p className="text-xs font-bold uppercase tracking-wide text-sky-700">Today’s outlook</p><div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><p><span className="text-slate-500">High / low:</span> <b className="text-slate-900">{Math.round(today.temperatureMax)}° / {Math.round(today.temperatureMin)}°C</b></p><p><span className="text-slate-500">Rain chance:</span> <b className="text-slate-900">{today.rainChance ?? 0}%</b></p><p><span className="text-slate-500">Expected condition:</span> <b className="text-slate-900">{condition(today.weatherCode)}</b></p></div></div>}</>}<p className="mt-4 text-[11px] text-slate-400">Condition time: {conditionTime ? conditionTime.toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short" }) : "—"}. Refreshes automatically every 10 minutes.</p></section>;
}
