import { Router } from "express";
import { farmerDirectoryDetail, registrations, reviewRegistration } from "../controllers/farmerController.js";
import { listFarmers } from "../models/farmerModel.js";
import { listUsers, updateUserAdministration } from "../models/userModel.js";
import { pool } from "../../config/db.js";
import { authenticate, allowRoles } from "../middleware/auth.js";
import { publishRealtimeUpdate } from "../services/realtimeService.js";
import { getNewReviewCounts, markReviewItemsSeen } from "../models/reviewIndicatorModel.js";
const router = Router();
router.use(authenticate, allowRoles("admin", "staff"));
router.get("/registrations", registrations);
router.get("/review-indicators", async (req, res, next) => { try { res.json(await getNewReviewCounts(req.user.id)); } catch (error) { next(error); } });
router.post("/review-indicators/:type/mark-seen", async (req, res, next) => { try { const counts = await markReviewItemsSeen(req.user.id, req.params.type); if (!counts) return res.status(422).json({ message: "Unknown review queue." }); res.json({ counts }); } catch (error) { next(error); } });
router.get("/registrations/:id", farmerDirectoryDetail);
router.patch("/registrations/:id", reviewRegistration);
router.get("/farmers", async (_req, res, next) => { try { res.json({ farmers: await listFarmers("approved") }); } catch (error) { next(error); } });
router.get("/farmers/:id", farmerDirectoryDetail);
router.get("/users", async (req, res, next) => { try { res.json({ users: await listUsers(req.query.role) }); } catch (error) { next(error); } });
router.get("/system-summary", allowRoles("admin"), async (_req, res, next) => { try { const [[counts], [roles], [registrations], [recentReports]] = await Promise.all([pool.query("SELECT (SELECT COUNT(*) FROM users) AS users, (SELECT COUNT(*) FROM farmer_profiles) AS farmers, (SELECT COUNT(*) FROM lands) AS lands, (SELECT COUNT(*) FROM damage_reports) AS reports, (SELECT COUNT(*) FROM damage_reports WHERE status = 'pending') AS pending_reports"), pool.query("SELECT role, COUNT(*) AS total FROM users GROUP BY role"), pool.query("SELECT registration_status AS status, COUNT(*) AS total FROM farmer_profiles GROUP BY registration_status"), pool.query("SELECT status, COUNT(*) AS total FROM damage_reports GROUP BY status")]); res.json({ counts, roles, registrations, reports: recentReports }); } catch (error) { next(error); } });
router.patch("/users/:id", allowRoles("admin"), async (req, res, next) => { try { const { role, isActive } = req.body; if (String(req.params.id) === String(req.user.id) && isActive === false) return res.status(422).json({ message: "You cannot disable your own account." }); if (role !== undefined && !["farmer", "staff", "technician", "admin"].includes(role)) return res.status(422).json({ message: "Choose a valid account role." }); if (isActive !== undefined && typeof isActive !== "boolean") return res.status(422).json({ message: "Account status must be true or false." }); const user = await updateUserAdministration(req.params.id, { role, isActive }); if (!user) return res.status(404).json({ message: "User was not found." }); publishRealtimeUpdate("user.updated"); res.json({ user }); } catch (error) { next(error); } });
export default router;
